version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: konzek
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: my_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  your_other_service:
    image: ghcr.io/tugberkurganci/app1:main
    container_name: 38d7239563fc0841e9fba5c98972b77b6829b2fbf1e79150af2e29b17c880677
    restart: always
    ports:
      - "8080:8080"
      - "2222:2222"
  
    
