name: Build
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: test
          POSTGRES_DB: konzek
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
      prometheus:
        image: prom/prometheus:v2.28.1
        ports:
          - 9090:9090
        options: --health-cmd "wget -qO- localhost:9090" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      matrix:
        image_name: ["app"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Extract image metadata for ${{ matrix.image_name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}

      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
         